spring.datasource.url=jdbc:mysql://localhost:3306/agenda_eventos
spring.datasource.username=Fernando
spring.datasource.password=LGK42017
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.jpa.open-in-view=false


spring.ai.ollama.enabled=true
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.model=phi3:latest
resend.api.key=re_FDYDbkXV_DrHoPJdDM8v7yrdEsSGgTdvh
api.security.token.secret=${JWT_SECRET:14172125}